variables:
  CONTAINER_IMAGE: $REG/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
  CONTAINER_NAME: $CI_PROJECT_NAME

build:
  tags:
    - ci-test
  script:
    - docker build --tag $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE

deploy:
  stage: deploy
  tags:
    - ci-test
  variables:
    DOCKER_HOST: $JOYRESERVE_DEMO
  script:
    - docker pull $CONTAINER_IMAGE
    - docker stop $CONTAINER_NAME || true
    - docker rm --force $CONTAINER_NAME || true
    - docker run --detach
      --name=$CONTAINER_NAME
      --net=test
      --label="traefik.enable=true"
      --label="traefik.http.routers.$CONTAINER_NAME.rule=Host(\`$CONTAINER_NAME.reserve.sya.org.cn\`)"
      --label="traefik.http.routers.$CONTAINER_NAME.tls.certResolver=myresolver"
      --label="traefik.http.routers.$CONTAINER_NAME-http.rule=Host(\`$CONTAINER_NAME.reserve.sya.org.cn\`)"
      --label="traefik.http.routers.$CONTAINER_NAME-http.middlewares=redirect-https@file"
      --volume="/etc/localtime:/etc/localtime:ro"
      $CONTAINER_IMAGE
