version: "3.3"

services:
  traefik:
    image: "traefik:3.0"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - "/etc/traefik:/etc/traefik"
      - "/var/lib/traefik:/var/lib/traefik"
      - "/var/log/traefik:/var/log/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      placement:
        constraints:
          - node.role == manager
