name: CI/CD

on:
  push:
    branches:
      - main

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
  PROJECT_NAME: bluegreen

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.IMAGE }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
            docker pull ${{ env.IMAGE }}
            docker run --detach \
              --name=${{ env.PROJECT_NAME }}-${{ github.sha }} \
              --label=${{ env.PROJECT_NAME }} \
              --network=main \
              ${{ env.IMAGE }}
            curl -if "http://localhost:10234/join?service=${{ env.PROJECT_NAME }}&port=8000&host=bl.mxsyx.site"
